name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: api
      run2:
        working-directory: client
    steps:
      - name: Install Npm Packages
        run: npm i
        run2: npm i
    
      - name: Init backend
        run: npm i
      
      - name: Init frontend
        run2: npm i
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start