name: Cypress Tests

on: push

jobs:
  cypress-run::
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: api
      start:
        working-directory: client

    steps:
      - uses: actions/checkout@v4
      - name: Checkout
      - name: Install Npm Packages
        start: npm i
        run: npm i
      - name: Init backend
        run: npm run dev
      - name: Init frontend
        start: npm run dev
      - name: Cypress run
        start: npx cypress run