name: Auto Tests

on: 
  push:
    paths:
     - api/**

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [20.x]
      
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Npm Packages
        run: npm ci
      - name: Unit Tests
        run: npm test unit_tests